import assert from 'node:assert/strict';
import {FireControl} from '../web/fire-control.js';
import {packTouch,unpackTouch,limitTouch,ALWAYS_POINT} from '../web/touch-input.js';
import {validInput,neutral} from '../web/frame-queue.js';
import {Netplay} from '../web/netplay.js';
const fire=new FireControl();
const run=(count,rapid,charge=false,start=0)=>Array.from({length:count},(_,i)=>fire.sample(typeof rapid==='function'?rapid(i):rapid,charge,(i+start)*1000/60));
const edges=values=>values.flatMap((v,i)=>v&&!values[i-1]?[i]:[]);
assert.deepEqual(edges(run(60,true)),[0,12,24,36,48]);
fire.reset();assert.deepEqual(edges(run(60,i=>i===0)),[0]);
fire.reset();assert(run(60,true,true).every(Boolean));
assert.equal(fire.sample(true,false,1000),false,'Releasing charge must release native shot');
assert(run(3,true,false,61).every(v=>!v),'Allow native charge release before rapid resumes');
assert.equal(fire.sample(true,false,64*1000/60),true);
fire.reset();run(19,true);const saved={...fire.state};
const expected=run(60,true,false,19);fire.state={...saved};
assert.deepEqual(run(60,true,false,19),expected,'Rollback restores exact shot cadence');
fire.reset();assert(run(60,false).every(v=>!v),'No automatic shots');
assert.equal(fire.sample(true,false,0,false),true,'Menus retain normal confirmation');
const packed=packTouch(16,{x:-320,y:180,active:true,unlimited:true,alwaysPoint:true});
assert.equal(limitTouch(packed,true),packed);
const limited=limitTouch(packed,false);
assert.deepEqual(unpackTouch(limited),{x:-320,y:180,active:true,unlimited:false});
assert(limited>=ALWAYS_POINT);assert.equal(limited%4096,16);
assert(validInput({...neutral(),actions:['rapid']}));
const network=Object.create(Netplay.prototype);
network.setLocal(new Set(['rapid']));network.setLocal(new Set());
assert.deepEqual(network.capture().actions,['rapid'],'A tap survives until the next network frame');
assert.deepEqual(network.capture().actions,[],'Tap is consumed exactly once');
console.log('PASS: 5 Hz, single tap, charge priority/release, rollback, menu, no autofire, room policy and network tap latch');
